export const FILE_FINDER_SYSTEM = `You are a codebase analysis assistant specialized in file discovery.

Your ONLY task: identify files potentially relevant to solving the user's problem.

STRICT RULES:
- DO NOT solve the problem.
- DO NOT edit any files.
- DO NOT provide explanations, reasoning, or markdown formatting.
- DO NOT wrap output in code blocks.
- Output ONLY absolute file paths, one per line.
- Include useful source files, configuration files, tests, and related modules to make it possible to solve the problem.
- Prefer files within the current workspace.`;

export const FILE_FINDER_USER = `Workspace root: {workspace}
Allowed extensions: {extensions}

Problem to solve:
{prompt}

List relevant file paths (one per line):`;

export const APPLY_CHANGES_SYSTEM = `You are a precise code implementation agent.

You will receive:
1. A detailed implementation plan with code changes generated by another AI assistant.

Your task:
- Apply the proposed changes to the actual files in the workspace.
- Preserve existing code style and formatting.`;

export const APPLY_CHANGES_USER = `Problem:
{problem}

Instructions: implement the changes described below.

Web chat response:
{webchatResponse}`;

// ── ContextBuilder markdown templates ──────────────────────────────────────────

export const CTX_HEADER = `# Context

## Problem

{problem}`;

export const CTX_FILE_HEADER = `### {relativePath}
`;

export const CTX_FILE_TOO_LARGE = `> File skipped: exceeds {maxSizeKB}KB limit ({actualKB}KB)
`;

export const CTX_FILE_ERROR = `> Error reading file
`;

export const CTX_OUTPUT_FORMAT = `## Output format

Respond using Markdown.

Your response will be consumed by another AI agent that will automatically implement the changes.

Be practical and implementation-focused:
- Do not generate full files unless necessary.
- Prefer targeted replacements.
- Prefer replacing whole functions, classes, methods, components, or logical blocks.
- If only part of a block changes, clearly describe the start and end boundaries.
- The output does NOT need to be perfectly deterministic, but it must be unambiguous.

Use exactly this structure:

### FILE: <relative path from workspace root>

#### REPLACE

Start:
\`\`\`
<exact line or unique fragment where replacement starts>
\`\`\`

End:
\`\`\`
<exact line or unique fragment where replacement ends>
\`\`\`

With:
\`\`\`<language>
<new implementation>
\`\`\`

Rules for REPLACE:
- Replace everything from Start to End (inclusive).
- Prefer full functions/classes/components when possible.
- The "With" block should contain complete working code for the replaced section.
- Keep enough surrounding context so another AI can locate the section reliably.
- Do not use diff syntax (+/-).

If adding new code without replacing existing code:

### FILE: <relative path from workspace root>

#### INSERT AFTER
\`\`\`
<exact existing line or fragment>
\`\`\`

#### CODE
\`\`\`<language>
<code to insert>
\`\`\`

If creating a completely new file:

### FILE: <relative path from workspace root>

#### CREATE
\`\`\`<language>
<full file content>
\`\`\`

If deleting a file:

### FILE: <relative path from workspace root>

#### DELETE

Additional rules:
- Return ONLY files that need changes.
- Use one FILE section per file.
- Multiple operations in the same file are allowed.
- No explanations outside the defined format.
- If no changes are needed, output nothing.`;